### ISSUE TITLE
[Bug]: Exec format error

### ISSUE THREAD

**Issue by eng-gabrielscardoso** [laravel/vs-code-extension#36]
### Extension Version

v0.1.11

### PHP Binary

Local PHP

### Operating System

Linux

### What happened?

**Context**

I have installed it today and when opened my application this issue happened the moment I opened any PHP file

![image](https://github.com/user-attachments/assets/2a232b59-f282-4871-8962-9e0f2b6547fe)

**Clipboard return**

```sh
/bin/sh: 1: /home/gabriel/.config/Code/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error
```

### Mimimal Code Sample

```php
# In this case, it occurs every time I open a PHP or Blade file in my Laravel application
```

**Comment by binaryfire** [comment]
Same. 

![image](https://github.com/user-attachments/assets/54f4f7ec-591c-4753-a48e-6132a551e4d3)

```
2024-12-17 02:50:28.576 [info] Activating Laravel Extension...
2024-12-17 02:50:28.576 [info] Started
2024-12-17 02:50:28.578 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.184 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.184 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.184 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.184 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.184 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.184 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.184 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.185 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 02:50:30.187 [error] Error:
 Translation namespaces

__VSCODE_LARAVEL_START_OUTPUT__{......
2024-12-17 02:50:30.187 [error] /usr/bin/php -r "
define('LARAVEL_START', microtime(true));

require_once '/home/binaryfire/workspace/myapp/vendor/autoload.php';
\$app = require_once '/home/binaryfire/workspace/myapp/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists(\$this->app['log'], 'setHandlers')) {
            \$this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

\$app->register(new VsCodeLaravel(\$app));
\$kernel = \$app->make(Illuminate\Contracts\Console\Kernel::class);
\$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 function vsCodeTranslationValue(\$key, \$value, \$file, \$lines): array {     \$lineNumber = 1;     \$keys = explode('.', \$key);     \$index = 0;     \$currentKey = array_shift(\$keys);      while (\$currentKey !== null && \$index < count(\$lines)) {         \$line = \$lines[\$index][1];          if (strpos(\$line, '\"' . \$currentKey . '\"', 0) !== false || strpos(\$line, \"'\" . \$currentKey . \"'\", 0) !== false) {             \$lineNumber = \$lines[\$index][0];             \$currentKey = array_shift(\$keys);         }          \$index++;     }      return [         'value' => \$value,         'path' => realpath(\$file),         'line' => \$lineNumber,         'params' => preg_match_all('/\:([A-Za-z0-9_]+)/', \$value, \$matches) ? \$matches[1] : [],     ]; }  function vscodeCollectTranslations(string \$path, string \$namespace = null) {     return collect(glob(\"{\$path}/**/*.{php,json}\", GLOB_BRACE))->map(function (\$file) use (\$path, \$namespace) {         \$key = pathinfo(\$file, PATHINFO_FILENAME);          if (\$namespace) {             \$key = \"{\$namespace}::{\$key}\";         }          \$lang = collect(explode('/', str_replace(\$path, '', \$file)))->filter()->first();          \$fileLines = explode(PHP_EOL, file_get_contents(\$file));         \$lines = [];         \$inComment = false;          foreach (\$fileLines as \$index => \$line) {             \$trimmed = trim(\$line);              if (substr(\$trimmed, 0, 2) === '/*') {                 \$inComment = true;                 continue;             }              if (\$inComment) {                 if (substr(\$trimmed, -2) !== '*/') {                     continue;                 }                  \$inComment = false;             }              if (substr(\$trimmed, 0, 2) === '//') {                 continue;             }              \$lines[] = [\$index + 1, \$trimmed];         }          return [             'key' => \$key,             'lang' => \$lang,             'values' => collect(\Illuminate\Support\Arr::dot(__(\$key, [], \$lang)))->map(function (\$value, \$key) use (\$file, \$lines) {                 if (is_array(\$value)) {                     return null;                 }                  return vsCodeTranslationValue(\$key, \$value, \$file, \$lines);             })->filter(),         ];     }); }  \$loader = app(\"translator\")->getLoader(); \$namespaces = \$loader->namespaces();  \$reflection = new ReflectionClass(\$loader); \$property = \$reflection->hasProperty(\"paths\")   ? \$reflection->getProperty(\"paths\")   : \$reflection->getProperty(\"path\"); \$property->setAccessible(true);  \$paths = \Illuminate\Support\Arr::wrap(\$property->getValue(\$loader));  \$default = collect(\$paths)->flatMap(function (\$path) {   return vscodeCollectTranslations(\$path); });  \$namespaced = collect(\$namespaces)->flatMap(function (\$path, \$namespace) {     return vscodeCollectTranslations(\$path, \$namespace); });  \$final = [];  foreach (\$default->merge(\$namespaced) as \$value) {     foreach (\$value['values'] as \$key => \$v) {         \$dotKey = \"{\$value['key']}.{\$key}\";          if (!isset(\$final[\$dotKey])) {             \$final[\$dotKey] = [];         }          \$final[\$dotKey][\$value['lang']] = \$v;          if (\$value['lang'] === \Illuminate\Support\Facades\App::currentLocale()) {             \$final[\$dotKey]['default'] = \$v;         }     } }  echo json_encode(\$final); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);
"
2024-12-17 02:50:30.187 [error] 
define('LARAVEL_START', microtime(true));

require_once '/home/binaryfire/workspace/myapp/vendor/autoload.php';
$app = require_once '/home/binaryfire/workspace/myapp/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists($this->app['log'], 'setHandlers')) {
            $this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

$app->register(new VsCodeLaravel($app));
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 function vsCodeTranslationValue($key, $value, $file, $lines): array {     $lineNumber = 1;     $keys = explode('.', $key);     $index = 0;     $currentKey = array_shift($keys);      while ($currentKey !== null && $index < count($lines)) {         $line = $lines[$index][1];          if (strpos($line, '"' . $currentKey . '"', 0) !== false || strpos($line, "'" . $currentKey . "'", 0) !== false) {             $lineNumber = $lines[$index][0];             $currentKey = array_shift($keys);         }          $index++;     }      return [         'value' => $value,         'path' => realpath($file),         'line' => $lineNumber,         'params' => preg_match_all('/\:([A-Za-z0-9_]+)/', $value, $matches) ? $matches[1] : [],     ]; }  function vscodeCollectTranslations(string $path, string $namespace = null) {     return collect(glob("{$path}/**/*.{php,json}", GLOB_BRACE))->map(function ($file) use ($path, $namespace) {         $key = pathinfo($file, PATHINFO_FILENAME);          if ($namespace) {             $key = "{$namespace}::{$key}";         }          $lang = collect(explode('/', str_replace($path, '', $file)))->filter()->first();          $fileLines = explode(PHP_EOL, file_get_contents($file));         $lines = [];         $inComment = false;          foreach ($fileLines as $index => $line) {             $trimmed = trim($line);              if (substr($trimmed, 0, 2) === '/*') {                 $inComment = true;                 continue;             }              if ($inComment) {                 if (substr($trimmed, -2) !== '*/') {                     continue;                 }                  $inComment = false;             }              if (substr($trimmed, 0, 2) === '//') {                 continue;             }              $lines[] = [$index + 1, $trimmed];         }          return [             'key' => $key,             'lang' => $lang,             'values' => collect(\Illuminate\Support\Arr::dot(__($key, [], $lang)))->map(function ($value, $key) use ($file, $lines) {                 if (is_array($value)) {                     return null;                 }                  return vsCodeTranslationValue($key, $value, $file, $lines);             })->filter(),         ];     }); }  $loader = app("translator")->getLoader(); $namespaces = $loader->namespaces();  $reflection = new ReflectionClass($loader); $property = $reflection->hasProperty("paths")   ? $reflection->getProperty("paths")   : $reflection->getProperty("path"); $property->setAccessible(true);  $paths = \Illuminate\Support\Arr::wrap($property->getValue($loader));  $default = collect($paths)->flatMap(function ($path) {   return vscodeCollectTranslations($path); });  $namespaced = collect($namespaces)->flatMap(function ($path, $namespace) {     return vscodeCollectTranslations($path, $namespace); });  $final = [];  foreach ($default->merge($namespaced) as $value) {     foreach ($value['values'] as $key => $v) {         $dotKey = "{$value['key']}.{$key}";          if (!isset($final[$dotKey])) {             $final[$dotKey] = [];         }          $final[$dotKey][$value['lang']] = $v;          if ($value['lang'] === \Illuminate\Support\Facades\App::currentLocale()) {             $final[$dotKey]['default'] = $v;         }     } }  echo json_encode($final); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);

2024-12-17 02:50:30.207 [error] /bin/sh: 1: /home/binaryfire/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

```

**Comment by ivenspontes** [comment]
see #10

**Comment by binaryfire** [comment]
@ivenspontes Unfortunately this didn't solve the issue for me. I'm no longer getting the `Exec format error` but it's still crashing:

```
Error:
 Translation namespaces

__VSCODE_LARAVEL_START_OUTPUT__{.....
/usr/bin/php -r "
define('LARAVEL_START', microtime(true));

require_once '/home/binaryfire/workspace/myapp/vendor/autoload.php';
\$app = require_once '/home/binaryfire/workspace/myapp/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists(\$this->app['log'], 'setHandlers')) {
            \$this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

\$app->register(new VsCodeLaravel(\$app));
\$kernel = \$app->make(Illuminate\Contracts\Console\Kernel::class);
\$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 function vsCodeTranslationValue(\$key, \$value, \$file, \$lines): array {     \$lineNumber = 1;     \$keys = explode('.', \$key);     \$index = 0;     \$currentKey = array_shift(\$keys);      while (\$currentKey !== null && \$index < count(\$lines)) {         \$line = \$lines[\$index][1];          if (strpos(\$line, '\"' . \$currentKey . '\"', 0) !== false || strpos(\$line, \"'\" . \$currentKey . \"'\", 0) !== false) {             \$lineNumber = \$lines[\$index][0];             \$currentKey = array_shift(\$keys);         }          \$index++;     }      return [         'value' => \$value,         'path' => realpath(\$file),         'line' => \$lineNumber,         'params' => preg_match_all('/\:([A-Za-z0-9_]+)/', \$value, \$matches) ? \$matches[1] : [],     ]; }  function vscodeCollectTranslations(string \$path, string \$namespace = null) {     return collect(glob(\"{\$path}/**/*.{php,json}\", GLOB_BRACE))->map(function (\$file) use (\$path, \$namespace) {         \$key = pathinfo(\$file, PATHINFO_FILENAME);          if (\$namespace) {             \$key = \"{\$namespace}::{\$key}\";         }          \$lang = collect(explode('/', str_replace(\$path, '', \$file)))->filter()->first();          \$fileLines = explode(PHP_EOL, file_get_contents(\$file));         \$lines = [];         \$inComment = false;          foreach (\$fileLines as \$index => \$line) {             \$trimmed = trim(\$line);              if (substr(\$trimmed, 0, 2) === '/*') {                 \$inComment = true;                 continue;             }              if (\$inComment) {                 if (substr(\$trimmed, -2) !== '*/') {                     continue;                 }                  \$inComment = false;             }              if (substr(\$trimmed, 0, 2) === '//') {                 continue;             }              \$lines[] = [\$index + 1, \$trimmed];         }          return [             'key' => \$key,             'lang' => \$lang,             'values' => collect(\Illuminate\Support\Arr::dot(__(\$key, [], \$lang)))->map(function (\$value, \$key) use (\$file, \$lines) {                 if (is_array(\$value)) {                     return null;                 }                  return vsCodeTranslationValue(\$key, \$value, \$file, \$lines);             })->filter(),         ];     }); }  \$loader = app(\"translator\")->getLoader(); \$namespaces = \$loader->namespaces();  \$reflection = new ReflectionClass(\$loader); \$property = \$reflection->hasProperty(\"paths\")   ? \$reflection->getProperty(\"paths\")   : \$reflection->getProperty(\"path\"); \$property->setAccessible(true);  \$paths = \Illuminate\Support\Arr::wrap(\$property->getValue(\$loader));  \$default = collect(\$paths)->flatMap(function (\$path) {   return vscodeCollectTranslations(\$path); });  \$namespaced = collect(\$namespaces)->flatMap(function (\$path, \$namespace) {     return vscodeCollectTranslations(\$path, \$namespace); });  \$final = [];  foreach (\$default->merge(\$namespaced) as \$value) {     foreach (\$value['values'] as \$key => \$v) {         \$dotKey = \"{\$value['key']}.{\$key}\";          if (!isset(\$final[\$dotKey])) {             \$final[\$dotKey] = [];         }          \$final[\$dotKey][\$value['lang']] = \$v;          if (\$value['lang'] === \Illuminate\Support\Facades\App::currentLocale()) {             \$final[\$dotKey]['default'] = \$v;         }     } }  echo json_encode(\$final); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);
"
```

**Comment by Grazulex** [comment]
same for me : 
echo '__VSCODE_LARAVEL_START_OUTPUT__';
 function vsCodeTranslationValue($key, $value, $file, $lines): array {     $lineNumber = 1;     $keys = explode('.', $key);     $index = 0;     $currentKey = array_shift($keys);      while ($currentKey !== null && $index < count($lines)) {         $line = $lines[$index][1];          if (strpos($line, '"' . $currentKey . '"', 0) !== false || strpos($line, "'" . $currentKey . "'", 0) !== false) {             $lineNumber = $lines[$index][0];             $currentKey = array_shift($keys);         }          $index++;     }      return [         'value' => $value,         'path' => realpath($file),         'line' => $lineNumber,         'params' => preg_match_all('/\:([A-Za-z0-9_]+)/', $value, $matches) ? $matches[1] : [],     ]; }  function vscodeCollectTranslations(string $path, string $namespace = null) {     return collect(glob("{$path}/**/*.{php,json}", GLOB_BRACE))->map(function ($file) use ($path, $namespace) {         $key = pathinfo($file, PATHINFO_FILENAME);          if ($namespace) {             $key = "{$namespace}::{$key}";         }          $lang = collect(explode('/', str_replace($path, '', $file)))->filter()->first();          $fileLines = explode(PHP_EOL, file_get_contents($file));         $lines = [];         $inComment = false;          foreach ($fileLines as $index => $line) {             $trimmed = trim($line);              if (substr($trimmed, 0, 2) === '/*') {                 $inComment = true;                 continue;             }              if ($inComment) {                 if (substr($trimmed, -2) !== '*/') {                     continue;                 }                  $inComment = false;             }              if (substr($trimmed, 0, 2) === '//') {                 continue;             }              $lines[] = [$index + 1, $trimmed];         }          return [             'key' => $key,             'lang' => $lang,             'values' => collect(\Illuminate\Support\Arr::dot(__($key, [], $lang)))->map(function ($value, $key) use ($file, $lines) {                 if (is_array($value)) {                     return null;                 }                  return vsCodeTranslationValue($key, $value, $file, $lines);             })->filter(),         ];     }); }  $loader = app("translator")->getLoader(); $namespaces = $loader->namespaces();  $reflection = new ReflectionClass($loader); $property = $reflection->hasProperty("paths")   ? $reflection->getProperty("paths")   : $reflection->getProperty("path"); $property->setAccessible(true);  $paths = \Illuminate\Support\Arr::wrap($property->getValue($loader));  $default = collect($paths)->flatMap(function ($path) {   return vscodeCollectTranslations($path); });  $namespaced = collect($namespaces)->flatMap(function ($path, $namespace) {     return vscodeCollectTranslations($path, $namespace); });  $final = [];  foreach ($default->merge($namespaced) as $value) {     foreach ($value['values'] as $key => $v) {         $dotKey = "{$value['key']}.{$key}";          if (!isset($final[$dotKey])) {             $final[$dotKey] = [];         }          $final[$dotKey][$value['lang']] = $v;          if ($value['lang'] === \Illuminate\Support\Facades\App::currentLocale()) {             $final[$dotKey]['default'] = $v;         }     } }  echo json_encode($final); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);

**Comment by binaryfire** [comment]
@Grazulex Are you using the Remote Development extension? Or are you developing on your local machine?

**Comment by oldravian** [comment]
I'm using vsocde on WSL2. I got the same error

`024-12-17 12:00:04.991 [error] /bin/sh: 1: /home/habib/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error`

**Comment by baruchsheffi** [comment]
Hi everyone, I discovered a workaround for this issue: [(https://github.com/laravel/vs-code-extension/issues/10#issuecomment-2546271971)]

**Comment by Grazulex** [comment]
> @Grazulex Are you using the Remote Development extension? Or are you developing on your local machine?

local
and i have follow the process from #10 but I have always the same error

**Comment by joetannenbaum** [comment]
Still working on Windows, but we just released 0.1.12, does this help anyone else?

**Comment by binaryfire** [comment]
@joetannenbaum Working on Ubuntu 22.04! (via VS Code on Windows + Remote Dev Extension). Thanks :)

**Comment by Grazulex** [comment]
working now with new version. Thanks

**Comment by binaryfire** [comment]
@joetannenbaum Spoke too soon. Now I'm hitting a different error:

```
2024-12-18 01:48:01.600 [info] Activating Laravel Extension...
2024-12-18 01:48:01.600 [info] Started
2024-12-18 01:48:01.856 [error] 
In ScopedPropertyAccessExpressionParser.php line 20:
                                                                               
  Call to undefined method Microsoft\PhpParser\Node\Expression\Variable::getR  
  esolvedName()                                                                
                                                                               


2024-12-18 01:48:04.181 [error] 
In ScopedPropertyAccessExpressionParser.php line 20:
                                                                               
  Call to undefined method Microsoft\PhpParser\Node\Expression\Variable::getR  
  esolvedName()                                                                
                                                                               


2024-12-18 01:48:04.181 [error] 
In ScopedPropertyAccessExpressionParser.php line 20:
                                                                               
  Call to undefined method Microsoft\PhpParser\Node\Expression\Variable::getR  
  esolvedName()                                                                
                                                                               


2024-12-18 01:48:04.181 [error] 
In ScopedPropertyAccessExpressionParser.php line 20:
                                                                               
  Call to undefined method Microsoft\PhpParser\Node\Expression\Variable::getR  
  esolvedName()                                                                
                                                                               


2024-12-18 01:48:04.181 [error] 
In ScopedPropertyAccessExpressionParser.php line 20:
                                                                               
  Call to undefined method Microsoft\PhpParser\Node\Expression\Variable::getR  
  esolvedName()                                                                
                                                                               


2024-12-18 01:48:04.181 [error] 
In ScopedPropertyAccessExpressionParser.php line 20:
                                                                               
  Call to undefined method Microsoft\PhpParser\Node\Expression\Variable::getR  
  esolvedName()                                                                
                                                                               


2024-12-18 01:48:04.181 [error] 
In ScopedPropertyAccessExpressionParser.php line 20:
                                                                               
  Call to undefined method Microsoft\PhpParser\Node\Expression\Variable::getR  
  esolvedName()                                                                
                                                                               


2024-12-18 01:48:04.181 [error] 
In ScopedPropertyAccessExpressionParser.php line 20:
                                                                               
  Call to undefined method Microsoft\PhpParser\Node\Expression\Variable::getR  
  esolvedName()                                                                
                                                                               


2024-12-18 01:48:04.181 [error] 
In ScopedPropertyAccessExpressionParser.php line 20:
                                                                               
  Call to undefined method Microsoft\PhpParser\Node\Expression\Variable::getR  
  esolvedName()                                                                
                                                                               


2024-12-18 01:48:04.181 [error] 
In ScopedPropertyAccessExpressionParser.php line 20:
                                                                               
  Call to undefined method Microsoft\PhpParser\Node\Expression\Variable::getR  
  esolvedName()                                                                
                                                                               


2024-12-18 01:48:04.182 [error] 
In ScopedPropertyAccessExpressionParser.php line 20:
                                                                               
  Call to undefined method Microsoft\PhpParser\Node\Expression\Variable::getR  
  esolvedName()                                                                
                                                                               


2024-12-18 01:48:04.182 [error] 
In ScopedPropertyAccessExpressionParser.php line 20:
                                                                               
  Call to undefined method Microsoft\PhpParser\Node\Expression\Variable::getR  
  esolvedName()                                                                
                                                                               


2024-12-18 01:48:04.182 [error] 
In ScopedPropertyAccessExpressionParser.php line 20:
                                                                               
  Call to undefined method Microsoft\PhpParser\Node\Expression\Variable::getR  
  esolvedName()                                                                
```

**Comment by dicktornfeldt** [comment]
I have same issue as @binaryfire 

It works in the project where I initially installed the extension. But now when I opened another project X, I got that same issue.

Tested to disable, uninstall, install extension. But the issue persists. Then I opened another project Y, there I don't get the issue. But opening project X again, the issue persists.

**Comment by binaryfire** [comment]
> I have same issue as @binaryfire
> 
> It works in the project where I initially installed the extension. But now when I opened another project X, I got that same issue.
> 
> Tested to disable, uninstall, install extension. But the issue persists. Then I opened another project Y, there I don't get the issue. But opening project X again, the issue persists.

It’s random for me too. Sometimes it crashes (with the error I shared), sometimes it’s fine.

**Comment by joetannenbaum** [comment]
Binary is compiled for all supported platforms now, if you encounter other errors please open a new issue.
